### ISSUE TITLE
探索本地运行时遇到的一些问题

### ISSUE THREAD

**Issue by PaloMiku** [RavelloH/RTheme#10]
我在尝试程序本地构建运行（未来考虑在服务器本地部署）时遇到了一些问题，问题和解决过程已整理手记

https://www.sotkg.com/notes/11

希望作者可以查看解惑，或者在后期更新程序时有些思路？

**Comment by RavelloH** [comment]
感谢支持！

实际上目前v4仍处于早期阶段，这两个问题我之前部署测试的时候注意到了，主要是数据库初始化问题，本来设想是写个nodejs脚本来在build前检测数据库，并同步云端及本地的模型，这样以后如果部署了升级的版本应该也能正常使用prisma同步数据库。

第二个问题本来是想靠“初始化增加一篇hello world”来解决的，不过似乎看起来还是直接修复更快捷，感谢指正：）

目前RTheme实际上想做到的效果是“尽可能的在博客网页端完成操作”，后续可能会将config设置存储在数据库，并实现博客文章的动态增量再生（即创建新文章后，无需redeploy即可看到文章），这样的话可能能将RTheme转变为一个“基于serverless的动态站点”

实际上，现在除了这些还有很多问题，例如音乐播放器、页面进度条、文章目录、文章排序等功能都在重构过程中损坏了，修起来可能还是需要不少时间的😂

**Comment by PaloMiku** [comment]
原来如此，不管怎么说都是相当佩服作者，V3和V4在他对应发布的那个时候都成功给了我眼前一亮的感觉😆，也希望作者能够顺利完成重构工作。
